version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3.12-management-alpine"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"   # Porta padrão para o RabbitMQ (AMQP)
      - "15672:15672" # Porta para a interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: bjnuffmq
      RABBITMQ_DEFAULT_PASS: gj-YQIiEXyfxQxjsZtiYDKeXIT8ppUq7
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - rabbitmq
    restart: always

volumes:
  rabbitmq_data: